#   _____ _                 _       _____ ____                                      _
#  / ____(_)               | |     / ____/ __ \                                    | |
# | (___  _ _ __ ___  _ __ | | ___| |   | |  | |_ __ ___  _ __ ___   __ _ _ __   __| |___
#  \___ \| | '_ ` _ \| '_ \| |/ _ \ |   | |  | | '_ ` _ \| '_ ` _ \ / _` | '_ \ / _` / __|
#  ____) | | | | | | | |_) | |  __/ |___| |__| | | | | | | | | | | | (_| | | | | (_| \__ \
# |_____/|_|_| |_| |_| .__/|_|\___|\_____\____/|_| |_| |_|_| |_| |_|\__,_|_| |_|\__,_|___/
#  ____              | |      _              _            __ ___
# |  _ \            /\_|     | |            | |          /_ |__ \
# | |_) |_   _     /  \   ___| |__   ___  __| | ___  _ __ | |  ) |
# |  _ <| | | |   / /\ \ / __| '_ \ / _ \/ _` |/ _ \| '_ \| | / /
# | |_) | |_| |  / ____ \ (__| | | |  __/ (_| | (_) | | | | |/ /_
# |____/ \__, | /_/    \_\___|_| |_|\___|\__,_|\___/|_| |_|_|____|
#         __/ |
#        |___/

# Setup here the prefix for the plugin
Prefix: "§5[§bSimpleCommands§5] §r"

# Setup here the message when player don't have permission to execute this command
ErrorPermission: " You don't this permission to use this command"

# Setup here message on feed command
Feed:
  confirm: " Your food has been regenerated"
  error: " You canno't actually regenerate your food"
# Setup here message on heal command
Heal:
  confirm: " Your life has been regenerated"
  error: " You canno't actually regenerate your life"

# Setup here message for furnace command
Furnace:
  errorItemInHand: " This item can not be furnace"
  noblockInHand: " You must have any items in your hand"
  confirmFurnace: " You have furnace {count} {item}"